temp/v3/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'main#index'
  get 'login' => 'main#login'

end

temp/v3/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

temp/v3/app/controllers/main_controller.rb
class MainController < ApplicationController
  def index

  end

  def login
    @user = User.new
  end

  def signin
    # @user = User.new
    # @user = User.new(user_params)
    # binding.pry
    # @user = User.find_by_account(user_params[:account])
    # if !@user
    #   @user = User.new(user_params)
    #   if @user.save
    #     redirect_to :action => :index
    #   else
    #     render :action => :login
    #   end
    # elsif @user.password == params[:password]
    #   redirect_to :action => :index
    # else
    #     render :action => :login
    # end
  end

  private

  def user_params
    params.require( :user).permit( :account, :password)
  end

end

temp/v3/app/views/layouts/application.slim
doctype html
html
  head
    title = @page_title || "users"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    #header
      .l
        a href== root_path
          svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24" height="24" viewBox="0 0 24 24"
            path d="M22.262 10.468c-3.39-2.854-9.546-8.171-9.607-8.225l-0.655-0.563-0.652 0.563c-0.062 0.053-6.221 5.368-9.66 8.248-0.438 0.394-0.688 0.945-0.688 1.509 0 1.104 0.896 2 2 2h1v6c0 1.104 0.896 2 2 2h12c1.104 0 2-0.896 2-2v-6h1c1.104 0 2-0.896 2-2 0-0.598-0.275-1.161-0.738-1.532zM14 20h-4v-5h4v5zM18 12l0.002 8c-0.002 0-3.002 0-3.002 0v-6h-6v6h-3v-8h-3.001c2.765-2.312 7.315-6.227 9.001-7.68 1.686 1.453 6.234 5.367 9 7.681 0 0-3 0-3-0.001z" fill="#000000"
      .r
        a = link_to '登入', new_user_session_path
        ||
        a = link_to '登出', destroy_user_session_path, :method => :delete

    #container
      == yield

temp/v3/app/views/main/index.slim
.notice = notice
.alert = alert

/ = link_to '註冊', new_registration_path(:user)
/ = link_to '登入', new_session_path(:user)

temp/v3/app/views/main/login.slim
.login
  .container
    = form_for @user, :url => signin_path(@user, @post), :method => :post do |f|
      .row.split
        .l = f.label :account, '帳號'
        .r = f.text_field :account, :placeholder => '請輸入你的帳號吧！'
      .row.split
        .l = f.label :account, '密碼'
        .r = f.password_field :password, :placeholder => '請輸入你的密碼吧！'
      .row.ctrl
        .l 若未註冊，則會自動建立帳號。
        .r
          = f.submit '立馬登入', :class => 'oa-btn blue-btn'