temp/v1/config/routes.rb
Rails.application.routes.draw do
  get 'main' => 'main#index'
  resources :users
  resources :jobs

end

temp/v1/app/models/job.rb
class Job < ActiveRecord::Base
  validates_presence_of :name
  has_many :users
end

temp/v1/app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :account, :password, :name
  belongs_to :job
end

temp/v1/app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [ :show, :edit, :update, :destroy]

  def index
    # @jobs = Job.all
    @jobs = Job.includes(:users).all
    @page_title = '職業列表'
  end

  def new
    @job = Job.new
    @page_title = '新增職業'
  end

  def create
    @job = Job.new(job_params)
    if @job.save
      flash[:notice] = 'Job was successfully created'
      redirect_to :action => :index
    else
      flash[:error] = @job.errors.full_messages
      render :action => :new
    end
  end

  def show
    @page_title = "#{@job.name} 基本資訊"
  end

  def edit
    @page_title = "編輯 #{@job.name} 的基本資料"
  end

  def update
    if @job.update(job_params)
      flash[:notice] = 'Job was successfully updated'
      redirect_to :action => :show, :id => @job
    else
      flash[:error] = @job.errors.full_messages
      render :action => :edit
    end
  end

  def destroy
    if @job.destroy
      flash[:notice] = 'Job was successfully deleted'
    else
      flash[:error] = 'Delete job error'
    end
    redirect_to jobs_path
  end

  private

  def job_params
    params.require( :job).permit( :name)
  end

  def set_job
    @job = Job.find(params[:id])
  end

end

temp/v1/app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @page_title = '首頁'
  end
end

temp/v1/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [ :show, :edit, :update, :destroy]
  before_action :set_jobs, only: [ :new, :create, :edit, :update]

  def index
    @users = User.includes(:job).all
    @page_title = '使用者列表'
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = 'user was successfully created'
      redirect_to :action => :index
    else
      flash[:error] = @user.errors.full_messages
      render :action => :new
    end
  end

  def show
    @page_title = "#{@user.name} 的基本資料"
  end

  def update
    if @user.update(user_params)
      flash[:notice] = 'user was successfully updated'
      redirect_to :action => :show, :id => @user
    else
      flash[:error] = @user.errors.full_messages
      render :action => :edit
    end
  end

  def destroy
    if @user.destroy
      flash[:notice] = 'User was successfully deleted'
    else
      flash[:error] = 'Delete user error'
    end

    redirect_to users_path
  end

  def new
    @user = User.new
    @page_title = '新增使用者'
  end

  def edit
    @page_title = "編輯 #{@user.name} 的基本資料"
  end

  private

  def user_params
    params.require( :user).permit( :name, :account, :password, :job_id)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def set_jobs
    @jobs = Job.all
  end
end

temp/v1/app/helpers/jobs_helper.rb
module JobsHelper
end

temp/v1/app/views/jobs/_form.html.erb
<%= f.label :name, "Name" %>
<%= f.text_field :name %>
<br />

temp/v1/app/views/jobs/edit.html.erb
<%= form_for @job do |f| %>
  <%= render "form", f: f %>
  <hr />
  <%= f.submit "Update" %>
<% end %>

temp/v1/app/views/jobs/index.html.erb
<%= link_to '回首頁', main_path %>
|
<%= link_to '新增職業', new_job_path %>
<hr/>

<% if @jobs.present? %>
  <table>
   <thead>
    <tr>
       <th>id</th>
       <th>name</th>
       <th>created_at</th>
       <th>users</th>

       <th>show</th>
       <th>edit</th>
       <th>delete</th>
    </tr>
   </thead>
   <tbody>
   <% @jobs.each do |job| %>
        <tr>
           <th><%= job.id %></th>
           <th><%= job.name %></th>
           <th><%= job.created_at %></th>
           <th><%= job.users.present? ? job.users.map { |user| [user.name] }.join(', ') : '' %></th>
           <th><%= link_to 'show', job_path(job) %></th>
           <th><%= link_to 'edit', edit_job_path(job) %></th>
           <th><%= link_to 'delete', job_path(job), :method => :delete%></th>
        </tr>
   <% end %>
   </tbody>
  </table>
<% else %>
  <div>No any data.</div>
<% end %>

temp/v1/app/views/jobs/new.html.erb
<%= form_for @job do |f| %>
  <%= render "form", f: f %>
  <hr />
  <%= f.submit "Create" %>
<% end %>

temp/v1/app/views/jobs/show.html.erb
Job ID: <%= @job.id %>
<br/>
Job Name: <%= @job.name %>
<br/>
Job Create Time: <%= @job.created_at %>
<br/>
Job Update Time: <%= @job.updated_at %>
<hr/>
<% if @job.users.present? %>
    <table>
      <thead>
        <tr>
          <th>id</th>
          <th>name</th>
          <th>view</th>
        </tr>
      </thead>
      <tbody>
        <% @job.users.each do |user| %>
            <tr>
              <td><%= user.id %></td>
              <td><%= user.name %></td>
              <td><%= link_to 'view', user_path(user) %></td>
            </tr>
        <% end %>
      </tbody>
    </table>
<% else %>
  No any one.
<% end %>
<hr/>
<%= link_to '回列表', jobs_path %>

temp/v1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title || "Users application" %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p style="color: green">
  <%= flash[:notice] %>
</p>
<p style="color: red">
  <% flash[:error].present? && flash[:error].each do |e|%>
  <%= e %><br/>
  <% end %>
</p>

<%= yield %>

</body>
</html>

temp/v1/app/views/main/index.html.erb
<%= link_to '職業列表', jobs_path %>
|
<%= link_to '使用者列表', users_path %>

temp/v1/app/views/users/_form.html.erb
<%= f.label :name, "Name" %>
<%= f.text_field :name %>
<br />
<%= f.label :account, "Account" %>
<%= f.text_field :account %>
<br />
<%= f.label :password, "Password" %>
<%= f.password_field :password %>
<br />
<%= f.label :job_id, "Job" %>
<%= f.select( :job_id, jobs.map { |job| [job.name, job.id] }.insert(0, ['無', 0])) %>

temp/v1/app/views/users/edit.html.erb
<%= form_for @user do |f| %>
  <%= render "form", f: f, jobs: @jobs %>
  <hr />
  <%= f.submit "Update" %>
<% end %>

temp/v1/app/views/users/index.html.erb
<%= link_to '回首頁', main_path %>
|
<%= link_to '新增使用者', new_user_path %>
<hr/>

<% if @users.present? %>
  <table>
   <thead>
    <tr>
       <th>id</th>
       <th>name</th>
       <th>account</th>
       <th>password</th>
       <th>created_at</th>
       <th>job</th>

       <th>show</th>
       <th>edit</th>
       <th>delete</th>
    </tr>
   </thead>
   <tbody>
   <% @users.each do |user| %>
        <tr>
           <th><%= user.id %></th>
           <th><%= user.name %></th>
           <th><%= user.account %></th>
           <th><%= user.password %></th>
           <th><%= user.created_at %></th>
           <th><%= user.job ? (link_to user.job.name, job_path(user.job)) : '無' %></th>

           <th><%= link_to 'show', user_path(user) %></th>
           <th><%= link_to 'edit', edit_user_path(user) %></th>
           <th><%= link_to 'delete', user_path(user), :method => :delete%></th>
        </tr>
   <% end %>
   </tbody>
  </table>
<% else %>
  <div>No any data.</div>
<% end %>

temp/v1/app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <%= render "form", f: f, jobs: @jobs %>
  <hr />
  <%= f.submit "Create" %>
<% end %>

temp/v1/app/views/users/show.html.erb
User ID: <%= @user.id %>
<br/>
User Name: <%= @user.name %>
<br/>
User Account: <%= @user.account %>
<br/>
User Passowrd: <%= @user.password %>
<br/>
Job: <%= @user.job ? @user.job.name : '無' %>
<br/>
User Create Time: <%= @user.created_at %>
<br/>
User Update Time: <%= @user.updated_at %>
<hr/>
<%= link_to '回列表', users_path %>