temp/v2/config/routes.rb
Rails.application.routes.draw do

  resources :users do
    resources :posts, :controller => 'user_posts' do
        post 'enable' => 'user_posts#enable'
      end
  end

end

temp/v2/app/models/code.rb
class Code < ActiveRecord::Base
    has_many :user_codes
    has_many :users, :through => :user_codes
end

temp/v2/app/models/info.rb
class Info < ActiveRecord::Base
  belongs_to :user
end

temp/v2/app/models/post.rb
class Post < ActiveRecord::Base
  validates_presence_of :title
  belongs_to :user

  def open?
    self.is_enabled == 1
  end

  def closed?
    !self.open?
  end


  def open!
    self.is_enabled = 1
    self.save!
  end

  def close!
    self.is_enabled = 0
    self.save!
  end
end

temp/v2/app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :account, :name
  has_many :posts
  has_one :info
  has_many :user_codes
  has_many :codes, :through => :user_codes

  accepts_nested_attributes_for :info, :allow_destroy => true, :reject_if => :all_blank, update_only: true
end

temp/v2/app/models/user_code.rb
class UserCode < ActiveRecord::Base
  belongs_to :user
  belongs_to :code
end

temp/v2/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # before_action :get_user, only: [ :edit, :update, :destroy, :show]

  def index
    @page_title = '文章列表'
    @posts = Post.all;
  end

  def new
    @page_title = '新增文章'
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash['notice'] = 'Success!'
      redirect_to :action => :index
    else
      flash['error'] = 'Failure!'
      render :action => :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    @page_title = "編輯 #{@post.title}"
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = 'Success!'
      redirect_to :action => :index
    else
      flash[:error] = 'Failure!'
      render :action => :edit
    end
  end

  private

  def post_params
    params.require( :post).permit( :title, :user_id, :content)
  end
end

temp/v2/app/controllers/user_infos_controller.rb
class UserInfosController < ApplicationController
  before_action :find_user
  before_action :find_info, only: [ :show, :edit, :update, :destroy]

  def show
  end

  def new
    @info = @user.build_info
  end

  def create
    @info = @user.build_info( info_params )
    if @info.save
      flash['notice'] = 'Success!'
      redirect_to :action => :show
    else
      flash['error'] = 'Failure!'
      render :action => :new
    end
  end

  def edit
  end

  def update

    if @info.update( info_params )
      flash['notice'] = 'Success!'
      redirect_to :action => :show
    else
      flash['error'] = 'Failure!'
      render :action => :edit
    end
  end

  def destroy
    @info.destroy

    redirect_to :action => :show
  end

  private

  def find_user
    @user = User.find( params[:user_id] )
  end

  def info_params
    params.require( :info).permit( :nickname, :address)
  end

  def find_info
    @info = @user.info
  end
end

temp/v2/app/controllers/user_posts_controller.rb
class UserPostsController < ApplicationController
  before_action :find_user
  before_action :find_post, only: [ :show, :edit, :update, :destroy]

  def index
    @posts = @user.posts
    @page_title = "#{@user.name} 的文章列表"
  end

  def show
  end

  def new
    @post = @user.posts.build
    @page_title = "新增 #{@user.name} 的文章"
  end

  def create
    @post = @user.posts.build( post_params )
    if @post.save
      flash['notice'] = 'Success!'
      redirect_to :action => :index
    else
      flash['error'] = 'Failure!'
      render :action => :new
    end
  end

  def edit
    @page_title = "編輯 #{@user.name} 的文章"
  end

  def update
    if @post.update( post_params )
      flash['notice'] = 'Success!'
      redirect_to :action => :index
    else
      flash['error'] = 'Failure!'
      render :action => :new
    end
  end

  def destroy
    @post.destroy

    redirect_to :action => :index
  end

  def enable
    @post = @user.posts.find( params[:post_id] )
    if @post.closed?
      @post.open!
    else
      @post.close!
    end
    redirect_to :back
  end

  private

  def find_user
    @user = User.find( params[:user_id] )
  end

  def post_params
    params.require( :post).permit( :title, :content)
  end

  def find_post
    @post = @user.posts.find( params[:id] )
  end

end

temp/v2/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [ :edit, :update, :destroy, :show]

  def index
    @page_title = '使用者列表'
    @users = User.all
  end

  def new
    @page_title = '新增使用者'
    @user = User.new
  end

  def edit
    @page_title = "編輯 #{@user.name} 的基本資料"
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = 'Success!'
      redirect_to :action => :index
    else
      flash[:error] = 'Failure!'
      render :action => :new
    end
  end

  def update
    if @user.update(user_params)
      flash[:notice] = 'Success!'
      redirect_to :action => :index
    else
      flash[:error] = 'Failure!'
      render :action => :edit
    end
  end

  def destroy
    if @user.destroy
      flash[:notice] = 'Success!'
    else
      flash[:error] = 'Failure!'
    end
      redirect_to :action => :index
  end

  private

  def user_params
    params.require( :user).permit( :name, :account, :info_attributes => [:nickname, :address, :_destroy], :code_ids => [])
  end

  def find_user
    @user = User.find(params[:id])
  end
end

temp/v2/app/helpers/posts_helper.rb
module PostsHelper
end

temp/v2/app/helpers/user_infos_helper.rb
module UserInfosHelper
end

temp/v2/app/helpers/user_posts_helper.rb
module UserPostsHelper
end

temp/v2/app/helpers/users_helper.rb
module UsersHelper
  def setup_user(user)
      user.build_info unless user.info
      user
  end
end

temp/v2/app/views/posts/_form.slim
- flash.each do |key, msg|
  = content_tag :div, msg, class: key

= f.label :title, '標題'
= f.text_field :title

br
br

= f.label :user_id, '作者'
= f.select( :user_id, User.all.map { |user| [user.name, user.id] }.insert(0, ['無', 0]))

br
br

= f.label :content, '內容'
= f.text_area :content

temp/v2/app/views/posts/edit.slim
= form_for @post do |f|
  = render 'form', f: f
  hr
  = f.submit '新增'
  ||
  = link_to '回總文章列表', posts_path

temp/v2/app/views/posts/index.slim
= link_to '使用者列表', users_path
||
= link_to '新增', new_post_path

- flash.each do |key, msg|
  = content_tag :div, msg, class: key

hr

table
  thead
    tr
      th 編號
      th 作者
      th 標題
      th 編輯
      th 刪除
  tbody
    - @posts.each do |post|
      tr
        td = post.id
        td = post.user.name if post.user
        td = post.title
        td = link_to '編輯', edit_post_path(post)
        td = link_to '刪除', post_path(post), :method => :delete

temp/v2/app/views/posts/new.slim
= form_for @post do |f|
  = render 'form', f: f
  hr
  = f.submit '新增'
  ||
  = link_to '回總文章列表', posts_path

temp/v2/app/views/user_infos/_form.slim
table.form
  tbody
    tr
      th = f.label :user_name, '作者'
      td = @user.name
    tr
      th = f.label :nickname, '暱稱'
      td = f.text_field :nickname
    tr
      th = f.label :address, '住址'
      td = f.text_area :address

- flash.each do |key, msg|
  = content_tag :div, msg, class: key

temp/v2/app/views/user_infos/edit.slim
= form_for @info, :url => user_info_path(@user) do |f|
  = render 'form', f: f
  .control
    = f.submit '修改'
    = link_to '回使用者列表', users_path()

temp/v2/app/views/user_infos/new.slim
= form_for @info, :url => user_info_path(@user) do |f|
  = render 'form', f: f
  .control
    = f.submit '新增'
    = link_to '回使用者列表', users_path()

temp/v2/app/views/user_infos/show.slim
.nav
  = link_to '使用者列表', users_path()
  ||
  = link_to '新增(取代)進階資料', new_user_info_path()

- flash.each do |key, msg|
  = content_tag :div, msg, class: key

table.form
  tbody
    tr
      th 使用者名稱
      td = @user.name
    tr
      th 使用者帳號
      td = @user.account
    tr
      th 文章數
      td = @user.posts.count

hr

- if @user.info
    table.form
      tbody
        tr
          th 暱稱
          td = @user.info.nickname
        tr
          th 住址
          td = @user.info.address
        tr
          th 修改
          td
            = link_to '修改', edit_user_info_path(@user)
            |/
            = link_to '刪除', user_info_path(@user), :method => :delete
- else
  .notice
   | 目前沒有
   = @user.name
   | 任何進階資料

temp/v2/app/views/users/_form.slim
table.form
  tbody
    tr
      th = f.label :name, '名稱'
      td = f.text_field :name
    tr
      th = f.label :account, '帳號'
      td = f.text_field :account
    tr
      th = f.label :account, '進階資料'
      td = f.fields_for :info do |info_form|
          = render 'info_form', info_form: info_form
    tr
      th = f.label :code_ids, '技能'
      td = f.collection_check_boxes(:code_ids, Code.all, :id, :name) do |b|
        = b.label { b.check_box + b.text }

- flash.each do |key, msg|
  = content_tag :div, msg, class: key

temp/v2/app/views/users/_info_form.slim
table.sub
  tbody
    tr
      th = info_form.label :nickname, '暱稱'
      td = info_form.text_field :nickname
    tr
      th = info_form.label :address, '住址'
      td = info_form.text_field :address
    - unless info_form.object.new_record?
      tr
        th = info_form.label :_destroy, '移除'
        td = info_form.check_box :_destroy

temp/v2/app/views/users/edit.slim
= form_for setup_user(@user) do |f|
  = render 'form', f: f
  .control
    = f.submit '編輯'
    = link_to '回使用者列表', users_path

temp/v2/app/views/users/index.slim
.nav
  = link_to '新增使用者', new_user_path
  ||
  = link_to '新增使用者', new_user_path

- flash.each do |key, msg|
  = content_tag :div, msg, class: key

table.list
  thead
    tr
      th 編號
      th 名稱
      th 帳號
      th 技能
      th 文章數
      th 檢視
      th 編輯
      th 刪除
      / th 進階資料
  tbody
    - @users.each do |user|
      tr
        td = user.id
        td = user.name
        td = user.account
        td = user.codes.map { |code| code.name }.join(", ") if user.codes
        td = user.posts.count
        td = link_to '內容', user_posts_path(user)
        td = link_to '編輯', edit_user_path(user)
        td = link_to '刪除', user_path(user), :method => :delete
        / td = link_to '檢視', user_info_path(user)

temp/v2/app/views/users/new.slim
= form_for setup_user(@user) do |f|
  = render 'form', f: f
  .control
    = f.submit '新增'
    = link_to '回使用者列表', users_path